---
name: hmph-gpt

services:
  hmph-gpt:
    build: .
    container_name: hmph_gpt
    environment:
      - DEVELOPMENT=false # hot reload
    volumes:
      - .:/bot
    network_mode: host
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: hmph_gpt_postgres
    environment:
      POSTGRES_USER: hmph-gpt
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hmph-gpt
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    container_name: hmph_gpt_redis
    ports:
      - 6379:6379
